services:
    php-fpm:
        container_name: php_fpm
        build:
            context: ./docker/php
            dockerfile: php-fpm-dev.docker
        volumes:
            - ./:/var/www/app
            - ./docker/php/config/php.ini-${YII_ENV}:${PHP_INI_DIR:-default}/php.ini
            - ./docker/php/config/pool.d/www.conf-${YII_ENV}:${PHP_FPM_DIR:-default}/www.conf
        working_dir: /var/www/app
        tty: true
        extra_hosts:
            - host.docker.internal:host-gateway
        restart: unless-stopped
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"
        networks:
            - network
    php-cli:
        container_name: php_cli
        build:
            context: ./docker/php
            dockerfile: php-cli-dev.docker
        volumes:
            - ./:/var/www/app
            - ./docker/php/config/php-cli.ini-${YII_ENV}:${PHP_INI_DIR}/php.ini
        working_dir: /var/www/app
        restart: unless-stopped
        tty: true
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"
        networks:
            - network
    nginx:
        container_name: nginx
        build:
            context: ./docker/nginx
            dockerfile: nginx.docker
        ports:
            - "${NGINX_LOCAL_PORT:-14001}:${NGINX_CONTAINER_PORT:-80}"
        volumes:
            - ./:/var/www/app
            - ./docker/nginx/config/nginx.conf:/etc/nginx/nginx.conf
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"
        restart: unless-stopped
        depends_on:
            - php-fpm
        networks:
            - network
    database:
        container_name: database
        image: postgres:16-alpine
        ports:
            - "${DB_LOCAL_PORT:-5439}:5432"
        volumes:
            - database:/var/lib/postgresql/data
            - ./docker/postgres/postgresql.conf:/etc/postgresql/postgresql.conf
            - ./docker/postgres/pg_hba.conf:/etc/postgresql/pg_hba.conf
        environment:
            PGUSER: ${DB_USERNAME:-postgres}
            POSTGRES_DB: ${DB_DATABASE:-database}
            POSTGRES_USER: ${DB_USERNAME:-postgres}
            POSTGRES_PASSWORD: ${DB_PASSWORD:-secret!}
            POSTGRES_HOST_AUTH_METHOD: trust
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"
        restart: unless-stopped
        networks:
            - network
volumes:
    database:
        external: true

networks:
    network:
        external: true
